### PR TITLE
Precision fix

### PR DESCRIPTION
**Pull request by gtonkinhill**
Updated the convolution calculation to keep everything in log space. I ran into issues for large kappa values.

### CODE REVIEW

**Comment by thibautjombart** [comment]
Thanks for the PR! It looks good; @finlaycampbell can you check which some checks are failing on travis? 

@gtonkinhill just being curious: why use the `_` prefix to rename C++ procedures? And are backquotes needed here? I confess this is the first time I see their use, but it looks like the current names are standard, so normal quotes should do? Not asking for a change, just want to make sure I understand nuances ;) 

At any rate, this is the first PR from an external contributor, so really nice to see this one! =D

**Comment by gtonkinhill** [comment]
Hi @thibautjombart, 

I think the underscores are due to an update in Rcpp, see the change on 2017-07-02 at http://dirk.eddelbuettel.com/code/rcpp.changelog.html 

I don't have a view on whether they are better or not but I couldn't work out easily how to get Rcpp to preform the old way when building using devtools.

Thanks to both you and @finlaycampbell for a great package!

**Comment by thibautjombart** [comment]
Thanks for the pointer re underscores, makes sense!

Most welcome for the package. Would you mind adding yourself to the contributors in the DESCRIPTION file?

**Comment by finlaycampbell** [comment]
Thanks for the PR @gtonkinhill. I've had issues with Rcpp adding the underscores as well, in that it seems to cause the Travis checks to fail. I'm just testing a build on my fork that merges all your changes except the C++ ones, hopefully that passes and then we can merge.

**Comment by thibautjombart** [comment]
Travis might be running an outdated version of Rcpp? @finlaycampbell if the check passes on your computer and on appveyor, I'd go ahead a merge.

**Comment by finlaycampbell** [comment]
Turns out we were using an old version of testthat, so I've updated the tests and everything seems to be passing now. Cheers for the PR again, @gtonkinhill.

**Comment by thibautjombart** [comment]
Awesome, thanks to both of you for sorting this out!
@gtonkinhill you're now officially contributing to a RECON package - join us if you fancy:
http://www.repidemicsconsortium.org/
see 'about' -> join

**Comment by gtonkinhill** [comment]
Thanks @finlaycampbell for getting the tests working and thanks for the invitation to join RECON, I will definitely sign up.

**Pull request merged**
